#phase: 1
name: Docker-image-pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v7 
      - name: setup node
        uses: actions/setup-node@v3 
        with:
          node-version: '24'
      - name: checking node version
        run: node -v  
      - name: installing dependencies frontend 
        working-directory: frontend 
        run: npm ci 
      - name: installing dependencies backend
        working-directory: backend
        run: npm ci



      - name: testing pipeline
        run: echo "test passed"
      - name: build frontend 
        working-directory: frontend
        run: npm run build
      # - name: checking docker installation
      #   run: |
      #     docker --version
      #     docker info
      - name: build frontend docker image 
        working-directory: frontend
        run: docker build -t rajajunaiddev/frontend-notes-app:latest .
      - name: build backend docker image
        working-directory: backend
        run: docker build -t rajajunaiddev/backend-notes-app:latest .
      - name: Dockerhub login
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_NAME }}
          password: ${{ secrets.DOCKERHUB_SECRET }}
      - name: build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: |
            rajajunaiddev/backend-notes-app:latest
            rajajunaiddev/backend-notes-app:${{ github.sha }}
      - name: build and push frontend
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: |
            rajajunaiddev/frontend-notes-app:latest
            rajajunaiddev/frontend-notes-app:${{ github.sha }}
     




